### ISSUE TITLE
OpenAI or OpenAPI?

### ISSUE THREAD

**Issue by drmindle12358** [aws-samples/llm-gateway#88]
Last sentence of the project overview: through an 'OpenAI' interface? 
----------------------------------
Project Overview
This project provides sample code and CDK for deploying APIs which provide a secure and scalable interface with Amazon Bedrock.

This project allows users to deploy a Rest API that supports streaming streaming responses from Amazon Bedrock through an OpenAI interface

**Comment by mirodrr2** [comment]
OpenAI. Meaning that you can use the OpenAI client and consume Bedrock Models by overriding the base url to point to your llm-gateway

**Comment by drmindle12358** [comment]
Thanks for confirming it's 'OpenAI' client. Now do you mean OpenAI's [Python client](https://platform.openai.com/docs/libraries/python-library)? 

However the interface of the [BaseChatModel](https://github.com/aws-samples/llm-gateway/blob/main/lambdas/gateway/api/models/base.py#L17) in your repo doesn't looks like any of OpenAI's API interface, hence the confusion. Thanks for your response.

**Comment by mirodrr2** [comment]
Please give it a try yourself. It works with any OpenAI client as it implements the OpenAI interface.

I apologize if the implementation code is misleading

**Comment by mirodrr2** [comment]
closing. You can re-open if you have issues with the OpenAI python client
